export const LOAD_YELLOW_NOTICE = "LOAD_YELLOW_NOTICE";
export const LOAD_RED_NOTICE = "LOAD_RED_NOTICE";
export const LOAD_ALL_NOTICE = "LOAD_ALL_NOTICE";
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_CHECK_LIST = "FETCH_CHECK_LIST";
export const FETCH_DETAILS = "FETCH_DETAILS";
export const FETCH_DETAILS_PHOTO = "FETCH_DETAILS_PHOTO";
