export const types = {
  GET_PERSONS: "GET_PERSONS",
  GET_ALL: "GET_ALL",
  ADD_REPORT: "ADD_REPORT",
  GET_REPORTS: "GET_REPORTS",
  DELETE_REPORT: "DELETE_REPORT",
  UPDATE_REPORT: "UPDATE_REPORT",
};
